---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radcals-{{ .Values.component }}-{{ .Values.env }}-deployment
  namespace: radcals
  labels:
    owner: digital-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radcals-{{ .Values.component }}-{{ .Values.env }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: radcals-{{.Values.component}}-{{.Values.env}}
    spec:
      imagePullSecrets:
        - name: radcal-gitlab-registry
      containers:
        - name: radcals-{{.Values.component}}
          image: registry.gitlab.com/bostonscientific.com/io/re-docs:{{.Values.imageTag}}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
